project:
  type: book
  output-dir: docs
  preview:
    port: 2024
    browser: false

lang: zh

book:
  title: "PHP计算机程序与解释"
  author: "金太阳无敌"
  date: last-modified
  date-format: "YYYY/MM/DD"
  chapters:
    - index.qmd
    - 001_构造过程抽象.qmd
    - 002_构造数据抽象.qmd
    - 003_模块化、对象和状态.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



